import Head from 'next/head'
import {BsFillMoonStarsFill, BsWhatsapp} from 'react-icons/bs';
import {AiFillTwitterCircle, AiFillLinkedin, AiFillInstagram} from 'react-icons/ai';
import Image from 'next/image';
import logo from "../public/logo.png";
import deved from "../public/dev-ed-wave.png";
import design from "../public/design.png";
import code from "../public/code.png";
import consulting from "../public/consulting.png";
import web1 from "../public/web1.png";
import web2 from "../public/web2.png";
import web3 from "../public/web3.png";
import web4 from "../public/web4.png";
import web6 from "../public/web6.png";
import { useState } from 'react';

export default function Home() {
  const [darkMode, setDarkMode] = useState(false);

  return (
    <div className={`bg-black`}>
      <Head>
        <title>JJ-ONAHI</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        {/* <link rel="icon" href="/favicon.ico" /> */}
      </Head>

      <main className='bg-black text-white px-10 md:px-20 lg:px-40 dark:bg-gray-900'>
        <section className='min-h-screen'>
          <nav className='py-10 mb-12 flex justify-between'>
            <span className='text-2xl font-bold'>JJ.ONAHI</span>
            <ul className='flex items-center'>
              <li>
                {/* <BsFillMoonStarsFill onClick={() => setDarkMode(!darkMode)} className='cursor-pointer text-xl'/> */}
              </li>
              <li>
                <a className='bg-gradient-to-r bg-lime-950 to-teal-400 text-white px-4 py-2 rounded-md ml-8 dark:bg-teal-500' href="page">Resume</a>
              </li>
            </ul>
          </nav>
          <div className='text-center p-10 justify-center items-center flex flex-col'>
            <h2 className='text-5xl py-2 text-[#002C2F] font-medium md:text-6xl dark:text-teal-500'>Agana J Onahi</h2>
            <h3 className='text-2xl font-bold py-2 justify-center md:text-3xl'>Creator, Developer, Designer, and Marketer</h3>
            <p className='text-md py-5 leading-8 text-gray-300 md:text-xl max-w-lg mx-auto'>
              I am a software engineer, graphics designer, UI/UX designer, and marketing expert with years of experience developing strategic solutions for businesses and startups. I specialize in solving technical and real-life problems, crafting effective and innovative solutions.
            </p>
          </div>
          <div className='text-5xl flex justify-center gap-16 py-3 text-gray-300'>
            <a href="https://twitter.com/jewels_joseph"><AiFillTwitterCircle /></a>
            <a href="https://www.linkedin.com/in/onahi-joseph-349603222/"><AiFillLinkedin /></a>
            <a href="https://www.instagram.com/jj_josephjewels/"><AiFillInstagram /></a>
            <a href="https://wa.me/message/AR73FKBYUDO7H1"><BsWhatsapp /></a>
          </div>
          <div className='relative mx-auto bg-gradient-to-b from-teal-600 to-teal-200 rounded-full w-40 h-40 mt-10 overflow-hidden md:h-96 md:w-96'>
            <Image src={deved} alt="" layout='fill' objectFit='cover'/>
          </div>
        </section>
        <section>
        <div>
  <h3 className='text-2xl font-bold py-2 justify-center'>My Expertise</h3>
  <p className='text-md py-5 leading-8 text-gray-300'>
    I&apos;ve consulted for startups and collaborated with talented individuals to create digital products for both business and consumer users.
  </p>
</div>

          <div className="lg:flex gap-10">
            <div className="text-center shadow-lg p-10 rounded-xl my-10 bg-gray-300 flex-1">
              <Image src={design} width={100} height={100} alt='' />
              <h3 className="text-lg font-medium pt-8 pb-2">Stunning  Designs</h3>
              <p className="py-2 text-teal-900">Creating elegant designs suited for your needs following core design theory.</p>
              <h4 className="py-4 text-teal-600">Design Tools I Use</h4>
              <p className="text-gray-800 py-1">Photoshop</p>
              <p className="text-gray-800 py-1">Illustrator</p>
              <p className="text-gray-800 py-1">Canva</p>
            </div>
            <div className="text-center shadow-lg p-10 rounded-xl my-10 bg-gray-300 flex-1">
              <Image src={code} width={100} height={100} alt='' />
              <h3 className="text-lg font-medium pt-8 pb-2">Software Development</h3>
              <p className="py-2 text-teal-900">Trust me with these Languages and I will build the impossible!</p>
              <h4 className="py-4 text-teal-600">Languages Are:</h4>
              <p className="text-gray-800 py-1">HTML5/CSS3</p>
              <p className="text-gray-800 py-1">Tailwind CSS</p>
              <p className="text-gray-800 py-1">JavaScript</p>
              <p className="text-gray-800 py-1">React/React Native</p>
              <p className="text-gray-800 py-1">Python</p>
              <p className="text-gray-800 py-1">WordPress/PHP</p>
            </div>
            <div className="text-center shadow-lg p-10 rounded-xl my-10 bg-gray-300 flex-1">
              <Image src={consulting} width={100} height={100} alt='' />
              <h3 className="text-lg font-medium pt-8 pb-2">Creativity</h3>
              <p className="py-2 text-teal-900">Building products that changes an existing domain. And transforms an existing domain into new ones.</p>
              <h4 className="py-4 text-teal-600">Creative Designs</h4>
              <p className="text-gray-800 py-1">Graphics Designs</p>
              <p className="text-gray-800 py-1">Product Designs</p>
              <p className="text-gray-800 py-1">UI/UX Design</p>
              <p className="text-gray-800 py-1">Branding Design/Identity</p>
            </div>
          </div>
        </section>
        <section>
          <div>
            <h3 className='text-2xl font-bold py-2 justify-center'>Portfolio</h3>
            <p className='text-md py-5 leading-8 text-gray-300'>
              Combining the art of design with the art of programming. Translating software wireframes to actual code to produce visual elements of the application.
            </p>
            <h1 className='text-md font-bold py-5 leading-8 text-gray-300'>MY PROJECTS </h1>
          </div>
          <div className='flex flex-col gap-10 py-10 lg:flex-row lg:flex-wrap'>
            <div className='basis-1/2 flex-1'>
              <Image src={web1} className="rounded-lg object-cover" width={100} height={100} layout="responsive" alt='' />
              <a href="https://derexfinesse.com/">Link</a>
            </div>
            <div className='basis-1/3 flex-1'>
              <Image src={web2} className="rounded-lg object-cover" width={100} height={100} layout="responsive" alt='' />
            </div>
            <div className='basis-1/3 flex-1'>
              <Image src={web3} className="rounded-lg object-cover" width={100} height={100} layout="responsive" alt='' />
            </div>
            <div className='basis-1/3 flex-1'>
              <Image src={web4} className="rounded-lg object-cover" width={100} height={100} layout="responsive" alt='' />
            </div>
            <div className='basis-1/3 flex-1'>
              <ul>
                <li><h1 className='text-gray-300 font-bold'>Usefule Links:</h1></li>
                <li><a href="http://Vcphotels.com" className='text-gray-300'>Hotel Managment System</a></li>
                <li><a href="https://drax.ng/" className='text-gray-300'>Logistics and Transportation Application</a></li>
                <li><a href="https://vue-cars-shop.netlify.app/" className='text-gray-300'>Cars Shoping webApp</a></li>
                <li><a href="https://github.com/Agana-Joseph" className='text-gray-300'>My GitHub</a></li>
              </ul>
            </div>
            <div className='basis-1/3 flex-1'>
              <Image src={web6} className="rounded-lg object-cover" width={100} height={100} layout="responsive" alt='' />
            </div>
          </div>
        </section>
      </main>
    </div>
  )
}

